name: Deploy to kvass.tatar

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/kvass.tatar || (mkdir -p /var/www/kvass.tatar && cd /var/www/kvass.tatar)
            git pull || git clone git@github.com:kvassoedik/personal-site.git .
            npm install
            npm run build
            sudo systemctl restart kvass.service
