name: Deploy to kvass.tatar

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH with password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd /var/www/kvass.tatar || (mkdir -p /var/www/kvass.tatar && cd /var/www/kvass.tatar)
            if [ ! -d ".git" ]; then
              git clone https://github.com/kvassoedik/personal-site.git .
            else
              git pull
            fi
            npm install
            npm run build
            sudo systemctl restart kvass.service
